### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by bpmct** [damintsew/idea-shared-index-dockerfile#1]
I am also working on some automations for shared indexes and would like to use this Dockerfile. If it is free to use, could you add a license?

**Comment by damintsew** [comment]
Hi! Thanks for your interest in my project.
Yes, it's free. I'm going to add a license and write how to use this image

**Comment by damintsew** [comment]
license id done #2

**Comment by damintsew** [comment]
And update of the README.md here #3

**Comment by bpmct** [comment]
Awesome! Thank you, this will be very helpful :)
